version: '3.1'
services:
    compiler:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - idp_network
            - db_network

networks:
    idp_network:
        driver: bridge
    db_network:
        driver: bridge